apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: portfolio-website
  labels:
    app: portfolio-website
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-entry-point: https

spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - kadesingleton.com
      secretName: portfolio-tls
  rules:
    - host: kadesingleton.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-service
                port:
                  number: 80
