apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: deployment-patch.yaml
resources:
  - ../../base
  - ingress.yaml

images:
  - name: kodenobi/portfolio-website
    newTag: 9902ff4
