apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml

resources:
  - ../../base
  - service.yaml

namespace: ingress-nginx
