apiVersion: v1
kind: Service
metadata:
  name: portfolio-website
  namespace: portfolio-website
  labels:
    app: portfolio-website
spec:
  selector:
    app: portfolio-website
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
